from typing import TYPE_CHECKING, Optional, Protocol, runtime_checkable

if TYPE_CHECKING:
    from src.application.dto import PromocodeDto


@runtime_checkable
class PromocodeDao(Protocol):
    async def get_by_id(self, promocode_id: int) -> Optional["PromocodeDto"]: ...

    async def get_by_code(self, code: str) -> Optional["PromocodeDto"]: ...

    async def get_all(self) -> list["PromocodeDto"]: ...

    async def search_by_code(self, query: str) -> list["PromocodeDto"]: ...

    async def create(self, promocode: "PromocodeDto") -> "PromocodeDto": ...

    async def update(self, promocode: "PromocodeDto") -> Optional["PromocodeDto"]: ...

    async def delete(self, promocode_id: int) -> bool: ...

    async def count_activations(self, promocode_id: int) -> int: ...

    async def has_user_activated(self, user_telegram_id: int, promocode_id: int) -> bool: ...

    async def create_activation(self, promocode_id: int, user_telegram_id: int) -> None: ...
